{{- if not .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-svc
  namespace: {{ .Values.namespace | default "app" }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
{{- end }}
