{{- if .Values.vaultSecrets.enabled }}
{{- range .Values.vaultSecrets.secrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "app.fullname" $ }}-{{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  type: kv-v2
  mount: secret
  path: {{ .path }}
  destination:
    name: {{ include "app.fullname" $ }}-{{ .name }}
    create: true
  refreshAfter: {{ .refreshInterval | default "30s" }}
{{- end }}
{{- end }}
